_BASE_: "Base-RCNN-FPN.yaml"
MODEL:
    WEIGHTS: "../../../pretrained_weight/FAIR/model_final_280758.pkl"
    MASK_ON: False
    PIXEL_STD: [57.375, 57.120, 58.395]
    RESNETS:
        DEPTH: 50
    ROI_HEADS:
        NAME: "CustomROIHeads"
        NUM_CLASSES: 80 
        NMS_THRESH_TEST: 0.3
        SCORE_THRESH_TEST: 0.05
    BACKBONE:
        FREEZE_AT: 2
        NAME: "build_resnet_fpn_backbone"
DATASETS:
    TRAIN: ("HICO_DET_overfit",)
    TEST: ("HICO_DET_overfit",)
TEST:
    EVAL_PERIOD: 400000
SOLVER:
    CHECKPOINT_PERIOD: 100
    IMS_PER_BATCH: 1
    BASE_LR: 0.0001
    MAX_ITER: 5000 
    STEPS: (1000, 3500)
OUTPUT_DIR: "./outputs/overfit_test/"
