from detectron2.config import CfgNode as CN

def add_hico_base_config(cfg):

    _C = cfg
    
    _C.MODEL.OBJECT_ROI_HEADS = CN()
    _C.MODEL.OBJECT_ROI_HEADS.NAME=""
    _C.MODEL.OBJECT_ROI_HEADS.NUM_CLASSES= 80
    _C.MODEL.OBJECT_ROI_HEADS.NMS_THRESH_TEST=0.3
    _C.MODEL.OBJECT_ROI_HEADS.SCORE_THRESH_TEST=0.05
    _C.MODEL.OBJECT_ROI_HEADS.POOLER_RESOLUTION = 7
    _C.MODEL.OBJECT_ROI_HEADS.POOLER_SAMPLING_RATIO = 0
    _C.MODEL.OBJECT_ROI_HEADS.POOLER_TYPE = "ROIAlignV2"
    _C.MODEL.OBJECT_ROI_HEADS.IN_FEATURES = ["p2", "p3", "p4", "p5"]

    _C.MODEL.HUMAN_ROI_HEADS = CN()
    _C.MODEL.HUMAN_ROI_HEADS.NAME=""
    _C.MODEL.HUMAN_ROI_HEADS.NUM_CLASSES= 80
    _C.MODEL.HUMAN_ROI_HEADS.NMS_THRESH_TEST=0.3
    _C.MODEL.HUMAN_ROI_HEADS.SCORE_THRESH_TEST=0.05

